### ISSUE TITLE
visible password (icon switchable)

### ISSUE THREAD

**Issue by frikas** [docmcfly/loginViaEmail#2]
I would like to have the possibility to expose the password during typo3 felogin login, by typing on an icon. This would change the password from non-readable to readable. This would help user minimizing input errors on login process. 

Best regards
Fritz

**Comment by docmcfly** [comment]
Hi Fritz,

I would put such a feature in an extra extension. Because this interface helper has nothing to do with LoginViaEMail. 

The new extension would globally overwrite the fluid renderer for f:form.password and include this function. 

That is a good idea. I will spend the days to see if it works that easy ;-) 

Greetings Clemens

**Comment by docmcfly** [comment]
Hi Fritz,

I did a little research: 

The template for the FE-Login is below and `typo3/sysext/felogin/Resources/Private/Templates`. With the constant: `styles.content.loginform.templateFile` you can define an alternative position for your own template. 

My approach that the `fluid:form.password` basically provides such a function probably has an effect for all password fields but NOT for the password field of the standard FE login. This does not use the fluid password field. It uses pure HTML. 

I suppose because you cannot set the name of the GET/POST variable directly in the fluid password field, but this name is always dependent on the extension context.  

Tough luck... So you have to change the location of the template using the constant mentioned above. There you copy the "old" template and add your new feature. 
Under https://html.form.guide/html-form/html-input-type-password.html is well described how to do it... 

An extension with this feature I will only release when Typo3 uses the Fluid-Passwortfield at the FE-Login. 

Best regards 
Clemens
