### ISSUE TITLE
Installation Guide

### ISSUE THREAD

**Issue by utzmedien** [docmcfly/loginViaEmail#5]
Hello docmcfly :-)

Unfortunately I can't find any installation documentation for your extension.

Any tips how to use it? I know this is not an Issue for the Extension. 

Thanks
Stephan

**Comment by docmcfly** [comment]
Hi Stephan

Thank you for your comment and your wish. I had previously assumed that the extension was so trivial that it did not require any "installation documentation": 

1. install app
2. login via email works

In the extension description I wrote that the e-mail address from the web frontend profile is used and that the extension "FrontendLogin" (from the Typo3 standard package) additionally enables a login for the web frontend users via e-mail. 

If two users have an identical e-mail address in the profile, my extension will not work, of course. How should it? 
That's why I wrote the following in the extension description: 
"Only if the user name can be uniquely assigned to the e-mail address will ..." 

But I will take your suggestion and write a small "installation documentation" with the requirements and limitations soon.

Stay healthy and have some nice holidays...
DMF

**Comment by utzmedien** [comment]
Hi DMF

Thanks a lot for your detailed answer. I have read all the descriptions. I just don't know where this field should come. Just a screenshot how it looks or where this new field should be would be enought for me. Or a running example on a customer page from your. I have installed the extension on my 10.4.10 System.

Stay healthy and thanks a lot for this extension :-)
Stephan

**Comment by docmcfly** [comment]
Hi Stephan,

ahh, now I understand where the shoe pinches. So in the BE there is somewhere a list with the frontend users. If you open one of these frontend users and then go to the tab "Personal Data", you will find a field for the email address of the user. This email field is already present in the "Standard" installation. 

But how this field is filled or by whom is not the responsibility of my extension. There are certainly extensions where the web frontend users can maintain their personal data. :) 

Best regards
DMF

**Comment by utzmedien** [comment]
Hi DMC

Oh I misunderstood the extension completely :-(

I thought it's a login by E-Mail. Like this Extension -> https://extensions.typo3.org/extension/logmail/

Mail is send and then you can login with a link in the E-Mail.

Sorry for wasting your time.

Best regards
Stephan

**Comment by docmcfly** [comment]
Hi Stephan, 

thank you for your correction. I never thought of this kind of login. Then of course my extension name is a bit misleading. 

Best regards
DMF
